### ISSUE TITLE
AVI output broken

### ISSUE THREAD

**Issue by Doarom** [jpsdr/x264#17]
Seems like ```x264_x64.exe --output File.avi``` will generate "broken" files.
When played back with mpv/mpc the files will run at 600fps and ffmpeg will complain about "non monotonically increasing dts to muxer in stream".
The latest kMod release from 2017 works flawlessly though.

**Comment by jpsdr** [comment]
That's bad to hear, because unfortunately this is totaly out of my skill, i'm just barely able to just make the build. I didn't make the patches and even less understand them, and i have no knowledge on all the ffmpeg/lavs/etc.. stuff.
If it's broken it means unfortunately it's the end of avi ouput, and the feature will be removed (at the build, not the patches) on the next build.
I take a look at the code of the avi ouput patch, it's small and didn't notice anything, but again, absolutely not in my skills.

**Comment by jpsdr** [comment]
I've been able to get the avi ouput patch code from kmod, there is a small difference with the one i have, and it's in the dst part, so, maybe, there is a fix (even if i absolutely don't understand this part of the code and the why of the difference).
Can you provide me a email address i can send you a build for test ? I don't know exactly when i'll be able to make the build, but it shouldn't be too long.

**Comment by jpsdr** [comment]
I have a test build ready, so now i'm waiting for an email to send it to you.

**Comment by Doarom** [comment]
ahXaere7@airmail.cc should work.

**Comment by jpsdr** [comment]
I've send you a file.

**Comment by jpsdr** [comment]
So... Have you been able to test if the new file i've provided you fixed the issue ?

**Comment by jpsdr** [comment]
If i still don't have news after a while, i'll close the thread and don't care anymore about this issue.

**Comment by jpsdr** [comment]
Last chance to answer me before i make a new release from the new master commits...

**Comment by jpsdr** [comment]
No answer/feedback, issue closed !
