### ISSUE TITLE
" lavc [error]: could not get frame buffer "

### ISSUE THREAD

**Issue by legion7298** [jpsdr/x264#19]
Hi. First of all, I would like to express my respect and gratitude for your near-perfect work.
I'd like to inform you of the issue of one function error.

When I loaded the avs into your x264mod and encoded it with the following options, the following error occurred.

"x264mod --crf 15 --atrack 1 --acodec "auto" -o test.mkv capx."Avs"

-->

" lavc [error]: could not get frame buffer "

If the audio option is none, it is encoded normally without audio.

Currently, avs have built-in video+audio sources with the following logic:

" avermedia live gamer hd2 [capture board] -> Graphstudio -> Avisynth(directshowsource) -> x264mod"

When I play with a pot player or encode with ffmpeg, the results of audio+video normally come out (but the speed is terrible when I encode avs with ffmpeg).

I look forward to solving this audio encoding issue and creating a more perfect and wonderful work.

**Comment by jpsdr** [comment]
Unfortunately, this is totaly out of my skills... :(
I didn't make the patches, and have no idea how they work, and have no knowledge of the ffmpeg (so lavc) stuff.
I'm just being able to compile it, while they don't break any of the old patches (but maybe it's allready done and i have no knowledge)...
Just out of curiosity, just in case, but don't expect great thing...
Does it also occurs with the oldest avaible release here (the r2893).
If yes, it's dead...
If no, can you narrow when it occurs ? Between which releases ?
Again, don't expect great things, but if by any chance it occurs between two releases still avaible here, there is a small chance i can identify the why. And then, maybe a very small chance to figure out a fix.
The problems, is that a lot of the patches (audio, avi, etc...) are olds and use now deprecated/obsolete ffmpeg functions and methods, because since, ffmpeg has changed/evolved a lot. These patches were properly programmed/done at the time, but are not anymore now.
They need to be redonne, but i absolutely don't have the knowledge for this.

**Comment by jpsdr** [comment]
No feedback, subject closed.
