### ISSUE TITLE
ffms Patches

### ISSUE THREAD

**Issue by realfinder** [jpsdr/x264#5]
Recently I see that winthread versions has no ffms and find that http://komisar.gin.by/ has Patches for ffms

maybe can help you to get back ffms with winthread

http://komisar.gin.by/x.patch/no_c++11_threads.diff

http://komisar.gin.by/x.patch/fix_FFmpegInited.diff

http://komisar.gin.by/x.patch/fix_imp.1.diff

**Comment by jpsdr** [comment]
> Recently I see that winthread versions has no ffms and find that
> http://komisar.gin.by/ hass Patches for ffms
As explained on the github comment, the winthread version is build with 
a winthread version of gcc, this gcc version just can't build ffms 
despite all the patch i've tried, it produces an error.
This is totaly out of my knowledge.



----------------------------------------------------
And to boldly go where no man has gone before...
http://jpsdr.free.fr
https://github.com/jpsdr

**Comment by jpsdr** [comment]
On the 3, i only had two. I've applied the missing one. I'll try when doing next build (probably very soon), but honestly, don't have great expectations...

**Comment by realfinder** [comment]
I look forward to it cuz posix in x64 using direct lossless to lossy (will use ffms) has annoying deadlock in random place

**Comment by jpsdr** [comment]
Unfortunately, as i was afraid of...
`G:/msys32/mingw32/bin/../lib/gcc/i686-w64-mingw32/6.3.0/../../../../i686-w64-mingw32/lib/../lib/libiconv.a(localcharset.o):localcharset.c:(.text+0x8): undefined reference to _imp__GetACP@0
collect2.exe: error: ld returned 1 exit status
`
But there is progress, because before i didn't even reach the link i had an error during compilng, the third Komisar's patch i didn't have fixes this compile error.
Unfortunately, something else was waiting afterward... :(

**Comment by jpsdr** [comment]
Thanks to the tip provided by LordMulder (and the information you provided me with the fix i didn't have), i'm able to build a winthread version of x264 with ffms2. Will it work ? That's another story. I hope i'll be able  to make builds of new version, actualy on the new version the exe generate segmentation fault on some steps of the fprolie. The fetch and rebase must have screwed something, despite the fact that the differences this times were very small and where only on small files.

**Comment by jpsdr** [comment]
New winthread version has ffms2.
