### ISSUE TITLE
subtitles problems

### ISSUE THREAD

**Issue by kongfl888** [jpsdr/x264#6]
Hi,
A subtitles problem has been found with your tmod build. And "vsfilter.dll" have beed included to the folder. But the subtitles still take broken. Or maybe you can provide me a "vsfilter.dll" for test?
Thank you!

**Comment by jpsdr** [comment]
Ouch... Sorry, but this may be totaly out of my skills. I'm just trying to maintain an existing build because the original author gave up (otherwise i wouldn't have done it), but unfortunately issues corrections or modifications are totaly out of my knowledge. I don't have also any specific "vsfilter.dll" to provide, i don't do this kind of thing.
But i'm curious, what is exactly the script you're using and the encode command line ?
Because i don't understand how subtitles can be releated to x264 ? They can be inserted in the video with an avisynth script for exemple, but if it fail at this stage, it's not related to x264 but with the avisynth plugin.
I don't see the correlation with x264 and subtitiles here, so i need all the exact informations : script used, precise command line encode, etc...

**Comment by tuanden0** [comment]
@kongfl888:
You can try to use the same setting with default x264.exe (maybe in meGUI), then if you have same problem with subtitles so it's avisynth's problem. Please check your plugins folder that installed and copy/cut the vsfilter the paste it to plugins folder.
If you use the command --subtitle "path to your sub.ass" then it's your fault.
If you use x264_64 and avisynth+_64, x264_64 will be crashed. You must to set filtermod to 3 for VSfilter and use the VSfilter_64 not 32.
If you use x264_32  and avisynth+_32, You must to set filtermod to 3 for VSfilter.
If it's too hard too explain, please upload your error screenshot on here.

I'm using x264_64_2851_winthread of jpsdr to hardsub anime to watch it on the TV with my lil sis but I never met the same problem like you. 
I agree with jpsdr because there's no related between subtiles and x264.

**Comment by kongfl888** [comment]
@jpsdr Thank you! 
@tuanden0 Official branch can't support the command line “--subtitles” or "--sub", and I know that. But tmod add support for it, maybe "supported". So I want to try it, and fail... Thank you!

**Comment by kongfl888** [comment]
@jpsdr Thank you!
@tuanden0 Official branch can't support the command line “--subtitles” or "--sub", and I know that. But tmod adds support for it, maybe "supported". So I want to try it, and fail... Thank you!

**Comment by jpsdr** [comment]
I've found out the commit with the subtitles.
The probability to be broken in the time because of code evolution is very low, because it has his totaly added own code in another file, and not code added in an existing file.
The command line is "--sub", but, what i've found in the code is the following:
If you're in 64bits, it seems it's looking for "VSFilter64.dll", but if you're in 32bits, it seems it's looking for "VSFilter.dll". So, the first question would be: Do you have to correct names ?
After, if VSFilter evolved in a way it becomes incompatible with the actual code, in that case, unfortunately i wouldn't know what to do.
