### ISSUE TITLE
aq-sensitivity with aq-mode 2/3

### ISSUE THREAD

**Issue by ghost** [jpsdr/x264#8]
Hey,

is tweaking `aq-sensitivity` supposed to have an impact when using `aq-mode` 2 or 3? I could have sworn it used to work just fine, am I imagining things?

Cheers.

**Comment by jpsdr** [comment]
Yes, i think it should. Have you noticed something...? I don't remember recently any commit related to this part.
After, i'm not an x264 dev, just someone who try to keep a build, so, depend on the question, i'll not be able to answer.

**Comment by b0r0mir** [comment]
I've done a bunch of tests and it seems `--aq-sensitivity` is ignored with `--aq-mode` 2/3. I've tested tmod r2893, r2851, r2833 and r2744 32bit and 64bit posix and winthreads with various settings. I've compared tests with different `--aq-sensitivity` values and every single test involving `--aq-mode` 2/3 and otherwise identical settings produces identical results disregarding different `--aq-sensitivity` settings. As soon as I test with `--aq-mode` 1 it produces different results with different `--aq-sensitivity` values as you would expect it should.

**Comment by jpsdr** [comment]
I'm afraid it will probably be something i don't have the x264 necessary knowledge to answer.
After, maybe as AQ mode 2/3 is "Auto variance", the "auto" part made the setting with less effect.
Ah... Just noticed that it's a "new" parameter, exist only in the tmod version... I'll take a look, just in case, but don't have too much expectations, it's probably the expected behavior.

**Comment by jpsdr** [comment]
Ok... I've take a quick look at the original tmod code. This parameter has been added in the TriAQ patch, and indeed, has effect only in AQ mode 1.
